name: minishell

############# CONFIGURE THE BRANCHES TO RUN#########

on:
  push:
    branches: [development, builtins]

############## ENVIROMENT PREPARATION ##############

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
        enviroment: [xterm-256color]
    name: ${{matrix.os}}
    env:
      TERM: ${{matrix.enviroment}}
      
#################### TASKS ########################

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true
      
    - name: Make
      working-directory: minishell
      run: make
