name: minishell

############# CONFIGURE THE BRANCHES TO RUN#########

on:
  push:
    branches: [development, builtins]

############## ENVIROMENT PREPARATION ##############

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
        language: [ 'c' ]
        enviroment: [xterm-256color]
    name: ${{matrix.os}}
    env:
      TERM: ${{matrix.enviroment}}
      
#################### TASKS ########################

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}
      
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
      
    - name: Make
      working-directory: minishell
      run: make
