name: minishell

############# CONFIGURE THE BRANCHES TO RUN#########

on:
  push:
    branches: [development, builtins]

############## ENVIROMENT PREPARATION ##############

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [macos-latest]
        enviroment: [xterm-256color]
    name: ${{matrix.os}}
    env:
      TERM: ${{matrix.enviroment}}
      
#################### TASKS ########################

    steps:
    - uses: actions/checkout@v2
      with:
        path:  minishell
        
    - name: Checkout submodules
      run:  git submodule update --init --recursive
      
    - name: show env
      run: env
      
    - name: Make
      working-directory: minishell
      run: make
